### ISSUE TITLE
Pay-type not working 

### ISSUE THREAD

**Issue by baimurzin** [sanchezmarcos/binance-p2p-bot#20]
**Describe the bug**
>> npx binancio --ticker USDT --fiat RUB --operation BUY --pay-types Tinkoff
when use this line, I got "Fetching page 1" in console and script finish working. Instead of getting results. This bug I saw only with **Tinkoff pay-types** 

**To Reproduce**
run script with this command: npx binancio --ticker USDT --fiat RUB --operation BUY --pay-types Tinkoff
see no results, but they are in binance

**Desktop (please complete the following information):**
 - OS: Macos Apple M1

**Comment by sanchezmarcos** [comment]
Hello, how are you?
Looking at the request and the binance url, they refer to it as `TinkoffNew` instead of `Tinkoff`. 

https://p2p.binance.com/en/trade/TinkoffNew/USDT?fiat=RUB

<img width="601" alt="Captura de pantalla 2023-02-01 a la(s) 18 37 45" src="https://user-images.githubusercontent.com/204724/216169063-049d63be-521d-48fe-9c07-f8b5de13cc8d.png">

However, putting as payment type `TinkoffNew` says it is wrong and `Tinkoff` is correct. It seems to be an internal Binance technical inconsistency, not a Binancio problem.

<img width="1058" alt="Captura de pantalla 2023-02-01 a la(s) 18 40 08" src="https://user-images.githubusercontent.com/204724/216169578-63ca0aae-99f2-4bef-99a6-edea9a3b0716.png">

If you find more information please add it, thank you!

**Comment by sanchezmarcos** [comment]
**Update**
Maybe there is an error in our http request assembly. I will do some more tests and update.

**Comment by baimurzin** [comment]
Ok, whats up? 
Did you find out something on this issue?

**Comment by sanchezmarcos** [comment]
It is definitely an internal Binance problem related to that type of payment method. Sorry!
