### ISSUE TITLE
Historical values

### ISSUE THREAD

**Issue by laresbernardo** [sanchezmarcos/binance-p2p-bot#4]
Hi Marcos! Thanks for sharing this awesome tool/code with us. Do you think it could be possible to fetch historical results so we can compare min, med, max values in a range of dates?
Thanks again!!

**Comment by sanchezmarcos** [comment]
Hi @laresbernardo! Nice to get in touch!

At the moment I could not find a public binance API with the p2p logs.

**I see two options of how we could add this feature:**
1. Saving the results of each query in a local db or in json format on disk. It is partially useful and a cronjob could be added.
2. Use a public cloud to save the results of the queries of each Binancio user.

**Comment by sanchezmarcos** [comment]
Hi @laresbernardo! Nice to get in touch!
At the moment I could not find a public binance API with the p2p logs.

**I see two options of how we could add this feature:**
1. Saving the results of each query in a local db or in json format on disk. It is partially useful and a cronjob could be added.
2. Use a public cloud to save the results of the queries of each Binancio user. (e.g. Firebase, MongoDB Atlas)  I find it interesting as an experiment, but it would be exposed to attacks and inaccurate information.

I will see if I can think of any other option, any suggestion is welcome!
Thanks for the feedback.

**Comment by laresbernardo** [comment]
Thanks!! I'm looking for a way to analize the distribution of daily P2P transactions (currency / USDT) vs the official exchange rate. Looking closer at your code, I noticed you added ARS as default (so you must from Argentina). For our LATAM countries, we have crazy things happening in our economy (I'm Venezuelan, lived in Argentina until a couple of months ago, and am in Colombia now)... and having this trends are quite valuable to time buying/selling correctly.
Hopefully, you can help me come up with a solution no getting this data! 👍

**Comment by sanchezmarcos** [comment]
¡Es un placer enorme estar en contacto con un hermano venezolano! 
You are right! I'm from Argentina and I totally understand your point! 💸 

In my case, I had already tracked the cryptocurrencies and their price in USDT and I needed to calculate the median in local currency to be clear about how my investment was performing, this is where Binancio was born. 

What I did was set up a local MongoDB collection and a cronjob that saves the USDT @ ARS output generating a historical record every N times a day. Then I can see the historical analysis in my DeFi dashboard with graphs and setup alerts to take advantage of certain opportunities and to avoid certain risks.

<img width="472" alt="Captura de Pantalla 2021-06-18 a la(s) 20 12 32" src="https://user-images.githubusercontent.com/204724/122623198-908d6700-d071-11eb-8c47-1490cc24ff39.png">

To get the price of any cryptocurrency against USDT, try consuming this Binance API:
https://www.binance.com/bapi/asset/v2/public/asset-service/product/get-products?includeEtf=true

p.s:
If I have time on the weekend I will add a parameter so that the output is just a json, maybe useful for your case.
Let me know if you think I can help you.
Thanks!

**Comment by laresbernardo** [comment]
That's great @sanchezmarcos . Thanks for taking the time!
- I've noticed you also [had some issues](https://stackoverflow.com/questions/67793326/api-binance-p2p-i-only-access-a-part-only-the-buy-and-not-all-of-it-buy-and-s) scrapping the data. I couldn't replicate your request shared in StackOverFlow (left a comment there 3 days ago) running the same code in Python.
- Trying to use the `https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search` API, I'm adding `?asset=USDT&tradeType=BUY&fiat=COP` manually but no results either. Any idea where is the documentation for that `bapi/c2c...` API? It seems it has what I need but I can't seem to get it right.
- I successfully connected with my API credentials to other documented Binance APIs, but nothing on P2P.
- And having `bapi/asset/v2/public/asset-service/product/get-products?includeEtf=true` results is great but 1. doesn't havee historical values and 2. doesn't have actual P2P transactions (which is exactly what I need) exchanging cryptos (USDT...) for fiat (ARS/COP/...). Actually, your tool shows open "ads" but not actual transactions, right? I guess they're much better as they are "real" values.
